"""Trusted permission, policy, approval, and audit records."""

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID


class Permission(StrEnum):
    """Granular privileged capabilities recognized by the broker."""

    FILESYSTEM_READ = "filesystem.read"
    FILESYSTEM_WRITE = "filesystem.write"
    SCREEN_READ = "screen.read"
    COMPUTER_INPUT = "computer.input"
    CAMERA_READ = "camera.read"
    MICROPHONE_READ = "microphone.read"
    CLIPBOARD_READ = "clipboard.read"
    CLIPBOARD_WRITE = "clipboard.write"
    TERMINAL_EXECUTE = "terminal.execute"
    APPLICATION_LAUNCH = "application.launch"
    APPLICATION_INSTALL = "application.install"
    NETWORK_REQUEST = "network.request"
    CODE_MODIFY = "code.modify"
    SYSTEM_POWER = "system.power"


class Decision(StrEnum):
    """Complete policy decision set."""

    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"


class DecisionReason(StrEnum):
    """Stable, machine-readable reasons for permission outcomes."""

    POLICY_ALLOW = "policy_allow"
    POLICY_DENY = "policy_deny"
    POLICY_APPROVAL_REQUIRED = "policy_approval_required"
    NO_PERMISSIONS_REQUIRED = "no_permissions_required"
    UNKNOWN_PERMISSION = "unknown_permission"
    MALFORMED_PERMISSION = "malformed_permission"
    MALFORMED_ARGUMENTS = "malformed_arguments"
    MALFORMED_ACTION = "malformed_action"
    UNKNOWN_ACTION = "unknown_action"
    UNKNOWN_TOOL = "unknown_tool"
    TOOL_PERMISSION_MISMATCH = "tool_permission_mismatch"
    MALFORMED_SCOPE = "malformed_scope"
    SCOPE_OUTSIDE_POLICY = "scope_outside_policy"
    MISSING_POLICY = "missing_policy"
    POLICY_DISABLED = "policy_disabled"
    HARD_SAFETY_APPROVAL_REQUIRED = "hard_safety_approval_required"
    HARD_SAFETY_DENY = "hard_safety_deny"
    APPROVAL_PENDING = "approval_pending"
    APPROVAL_APPROVED = "approval_approved"
    APPROVAL_DENIED = "approval_denied"
    APPROVAL_EXPIRED = "approval_expired"
    APPROVAL_CANCELLED = "approval_cancelled"
    APPROVAL_CONSUMED = "approval_consumed"
    UNTRUSTED_APPROVER = "untrusted_approver"
    INVALID_REMEMBERED_GRANT = "invalid_remembered_grant"
    TASK_CANCELLED = "task_cancelled"


class Risk(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class SafetyClass(StrEnum):
    """Hard-policy action categories assigned by trusted tool code."""

    ORDINARY = "ordinary"
    BULK_DELETION = "bulk_deletion"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    DESTRUCTIVE_SYSTEM_COMMAND = "destructive_system_command"
    SOFTWARE_INSTALLATION = "software_installation"
    SELF_MODIFICATION = "self_modification"


class ApprovalStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    EXPIRED = "expired"
    CANCELLED = "cancelled"
    CONSUMED = "consumed"


class ApprovalChoice(StrEnum):
    APPROVE_ONCE = "approve_once"
    DENY_ONCE = "deny_once"
    APPROVE_LIMITED = "approve_limited"


class ApprovalActorKind(StrEnum):
    TRUSTED_USER = "trusted_user"
    MODEL = "model"
    TOOL = "tool"
    SYSTEM = "system"


class ApprovalSource(StrEnum):
    TRUSTED_UI = "trusted_ui"
    TRUSTED_LOCAL_API = "trusted_local_api"
    MODEL = "model"
    TOOL = "tool"
    SYSTEM = "system"


@dataclass(frozen=True, slots=True)
class PermissionScope:
    """Optional least-privilege constraints attached to one request."""

    paths: tuple[str, ...] = ()
    applications: tuple[str, ...] = ()
    hosts: tuple[str, ...] = ()
    command_families: tuple[str, ...] = ()
    tool_id: str | None = None
    task_id: UUID | None = None
    duration_seconds: int | None = None


@dataclass(frozen=True, slots=True)
class ScopeConstraint:
    """Trusted upper bounds declared by one policy rule."""

    paths: tuple[str, ...] = ()
    applications: tuple[str, ...] = ()
    hosts: tuple[str, ...] = ()
    command_families: tuple[str, ...] = ()
    tools: frozenset[str] = frozenset()
    tasks: frozenset[UUID] = frozenset()
    max_duration_seconds: int | None = None


@dataclass(frozen=True, slots=True)
class PermissionRequest:
    permission: Permission | str
    scope: PermissionScope


@dataclass(frozen=True, slots=True)
class SafeArgument:
    """A summary item generated by trusted application code."""

    name: str
    value: str


@dataclass(frozen=True, slots=True)
class ActionDescriptor:
    """Trusted description of an exact validated tool action."""

    action: str
    arguments_summary: tuple[SafeArgument, ...]
    risk: Risk
    permissions: tuple[PermissionRequest, ...]
    safety_class: SafetyClass = SafetyClass.ORDINARY


@dataclass(frozen=True, slots=True)
class PolicyRule:
    policy_id: str
    permission: Permission
    decision: Decision
    scope: ScopeConstraint
    actions: frozenset[str]
    enabled: bool = True


@dataclass(frozen=True, slots=True)
class PolicyEvaluation:
    decision: Decision
    reason: DecisionReason
    policy_id: str | None
    normalized_scope: PermissionScope | None
    permission: Permission | None = None


@dataclass(frozen=True, slots=True)
class ApprovalIdentity:
    identity_id: str
    kind: ApprovalActorKind


@dataclass(frozen=True, slots=True)
class ApprovalRequest:
    request_id: UUID
    task_id: UUID
    exact_action: str
    arguments_summary: tuple[SafeArgument, ...]
    argument_fingerprint: str
    permission: Permission
    risk: Risk
    scope: PermissionScope
    reason: DecisionReason
    policy_id: str
    created_at: datetime
    expires_at: datetime
    status: ApprovalStatus = ApprovalStatus.PENDING
    approval_identity: str | None = None
    approval_source: ApprovalSource | None = None


@dataclass(frozen=True, slots=True)
class RememberedGrant:
    grant_id: UUID
    permission: Permission
    scope: PermissionScope
    tool_id: str
    identity_id: str
    source: ApprovalSource
    created_at: datetime
    expires_at: datetime


@dataclass(frozen=True, slots=True)
class ApprovalDecisionResult:
    accepted: bool
    reason: DecisionReason
    request: ApprovalRequest | None


@dataclass(frozen=True, slots=True)
class AuthorizationReceipt:
    receipt_id: UUID
    task_id: UUID
    tool_id: str
    action: str
    argument_fingerprint: str
    argument_names: tuple[str, ...]
    evaluations: tuple[PolicyEvaluation, ...]
    approval_requests: tuple[ApprovalRequest, ...]
    remembered_grants: tuple[RememberedGrant, ...]
    user_id: str | None
    authorized_at: datetime


@dataclass(frozen=True, slots=True)
class AuthorizationResult:
    authorized: bool
    reason: DecisionReason
    receipt: AuthorizationReceipt | None = None
    approval_requests: tuple[ApprovalRequest, ...] = ()


@dataclass(frozen=True, slots=True)
class AuditRecord:
    time: datetime
    user_id: str | None
    task_id: UUID
    tool_id: str
    requested_permission: str | None
    action: str
    argument_names: tuple[str, ...]
    argument_fingerprint: str
    normalized_scope: PermissionScope | None
    policy_id: str | None
    decision: Decision
    reason: DecisionReason
    approval_identity: str | None
    approval_source: ApprovalSource | None
    execution_outcome: str
