"""Optional bounded multi-agent orchestration; single-agent remains the default."""

from jarvis.multi_agent.engine import (
    EvidenceMultiAgentGoalVerifier,
    MultiAgentCoordinator,
    MultiAgentGoalVerification,
    MultiAgentGoalVerifier,
    SingleAgentExecutor,
    SingleAgentOutcome,
)
from jarvis.multi_agent.models import (
    AgentContract,
    AgentInvocation,
    AgentNodeStatus,
    AgentResult,
    AgentResultStatus,
    AgentType,
    ContextItem,
    DelegatedTaskNode,
    DelegationGraph,
    EvidenceReference,
    ExecutionMode,
    OrchestrationRequest,
    OrchestrationResult,
    OrchestrationStatus,
    ResourceBudget,
    ResourceUsage,
)
from jarvis.multi_agent.registry import AgentRegistry, AgentRegistryError, AgentWorker
from jarvis.multi_agent.validation import (
    DelegationLimits,
    DelegationProposal,
    DelegationValidationError,
    DelegationValidationReason,
    DelegationValidator,
)

__all__ = [
    "AgentContract",
    "AgentInvocation",
    "AgentNodeStatus",
    "AgentRegistry",
    "AgentRegistryError",
    "AgentResult",
    "AgentResultStatus",
    "AgentType",
    "AgentWorker",
    "ContextItem",
    "DelegatedTaskNode",
    "DelegationGraph",
    "DelegationLimits",
    "DelegationProposal",
    "DelegationValidationError",
    "DelegationValidationReason",
    "DelegationValidator",
    "EvidenceReference",
    "EvidenceMultiAgentGoalVerifier",
    "ExecutionMode",
    "MultiAgentCoordinator",
    "MultiAgentGoalVerification",
    "MultiAgentGoalVerifier",
    "OrchestrationRequest",
    "OrchestrationResult",
    "OrchestrationStatus",
    "ResourceBudget",
    "ResourceUsage",
    "SingleAgentExecutor",
    "SingleAgentOutcome",
]
